# Generated by Django 5.1.6 on 2026-04-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_subcategoria'),
    ]

    operations = []
