# Generated by Codex on 2026-06-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0006_recetamedica_firma_digital_fecha_validez"),
        ("inventarios", "0013_alter_limitedispensacion_tenant"),
        ("tenants", "0001_initial"),
        ("tratamientos", "0009_alter_tratamientoactivo_estado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapturaReceta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archivo_imagen", models.ImageField(upload_to="prescripciones/capturas/")),
                ("nombre_archivo_original", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("procesada", "Procesada"),
                            ("confirmada", "Confirmada"),
                            ("fallida", "Fallida"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("motor_ia", models.CharField(default="gemini", max_length=60)),
                ("modelo_ia", models.CharField(blank=True, max_length=120)),
                ("texto_extraido", models.TextField(blank=True)),
                ("respuesta_ia", models.JSONField(blank=True, default=dict)),
                ("datos_extraidos", models.JSONField(blank=True, default=dict)),
                ("datos_resueltos", models.JSONField(blank=True, default=dict)),
                ("requiere_revision_manual", models.BooleanField(default=True)),
                ("error_detalle", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capturas_receta",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capturas_receta_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receta_medica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capturas_origen",
                        to="clientes.recetamedica",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Captura de receta",
                "verbose_name_plural": "Capturas de recetas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "estado"], name="prescripcio_tenant__830c4a_idx"),
                    models.Index(fields=["cliente", "created_at"], name="prescripcio_cliente_fdf7d7_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemCapturaReceta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("orden", models.PositiveIntegerField(default=1)),
                ("nombre_detectado", models.CharField(blank=True, max_length=255)),
                ("presentacion_detectada", models.CharField(blank=True, max_length=255)),
                ("cantidad_detectada", models.CharField(blank=True, max_length=120)),
                ("indicaciones_detectadas", models.TextField(blank=True)),
                ("duracion_detectada", models.CharField(blank=True, max_length=120)),
                ("confianza", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                (
                    "decision_cliente",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aceptado", "Aceptado"),
                            ("rechazado", "Rechazado"),
                            ("editado", "Editado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("nombre_resuelto", models.CharField(blank=True, max_length=255)),
                ("indicaciones_resueltas", models.TextField(blank=True)),
                ("duracion_resuelta", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "captura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="prescripciones.capturareceta",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_captura_receta",
                        to="inventarios.producto",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "tratamiento_base",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_captura_receta",
                        to="tratamientos.tratamientobase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de captura de receta",
                "verbose_name_plural": "Items de captura de receta",
                "ordering": ["orden", "id"],
                "indexes": [
                    models.Index(
                        fields=["captura", "decision_cliente"],
                        name="prescripcio_captura_1cf0fd_idx",
                    ),
                ],
            },
        ),
    ]
